# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Search

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v4

      - name: Build App (Release)
        run: swift build -c release -v

      - name: Run tests
        run: swift test -v

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Search-macOS-x86_64
          path: .build/x86_64-apple-macosx/release/Search
